In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [15]:
vectorizer = CountVectorizer()

In [16]:
type(vectorizer)

sklearn.feature_extraction.text.CountVectorizer

In [17]:
# Stop words - The, a, an, is

data =  ["The cat sat on the mat.", 
    "This cat is a nice cat.",
    "That cat is a good one"]

In [18]:
vectorizer.fit(data)

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [19]:
vectorizer.vocabulary_

{u'cat': 0,
 u'good': 1,
 u'is': 2,
 u'mat': 3,
 u'nice': 4,
 u'on': 5,
 u'one': 6,
 u'sat': 7,
 u'that': 8,
 u'the': 9,
 u'this': 10}

In [20]:
data_vec = vectorizer.transform(data)

In [21]:
data_vec = data_vec.toarray()

In [22]:
data_vec

array([[1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0],
       [2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0]])

In [23]:
data

['The cat sat on the mat.',
 'This cat is a nice cat.',
 'That cat is a good one']

In [24]:
vectorizer2 = TfidfVectorizer()

In [ ]:
# term frequencey / document frequency  = term frequencey * (document frequency )^-1

In [25]:
vectorizer2.fit(data)

TfidfVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm=u'l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern=u'(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [26]:
vectorizer2.vocabulary_

{u'cat': 0,
 u'good': 1,
 u'is': 2,
 u'mat': 3,
 u'nice': 4,
 u'on': 5,
 u'one': 6,
 u'sat': 7,
 u'that': 8,
 u'the': 9,
 u'this': 10}

In [28]:
vectorizer2.transform(data).toarray()

array([[0.21786941, 0.        , 0.        , 0.36888498, 0.        ,
        0.36888498, 0.        , 0.36888498, 0.        , 0.73776997,
        0.        ],
       [0.59256672, 0.        , 0.38151877, 0.        , 0.50165133,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.50165133],
       [0.29803159, 0.50461134, 0.38376993, 0.        , 0.        ,
        0.        , 0.50461134, 0.        , 0.50461134, 0.        ,
        0.        ]])

In [29]:
data

['The cat sat on the mat.',
 'This cat is a nice cat.',
 'That cat is a good one']

In [36]:
# 2-gram ; 3
# The_cat 
# cat_sat
# sat_on
# on_the
# the_mat

vectorizer = TfidfVectorizer(analyzer='char', ngram_range=(1,3))

In [37]:
vectorizer.fit(
    [
    "The cat sat on the mat.",
    "This cat is a nice cat.",
    "That cat is a good one",
])
vectorizer.vocabulary_

{u' ': 0,
 u' a': 1,
 u' a ': 2,
 u' c': 3,
 u' ca': 4,
 u' g': 5,
 u' go': 6,
 u' i': 7,
 u' is': 8,
 u' m': 9,
 u' ma': 10,
 u' n': 11,
 u' ni': 12,
 u' o': 13,
 u' on': 14,
 u' s': 15,
 u' sa': 16,
 u' t': 17,
 u' th': 18,
 u'.': 19,
 u'a': 20,
 u'a ': 21,
 u'a g': 22,
 u'a n': 23,
 u'at': 24,
 u'at ': 25,
 u'at.': 26,
 u'c': 27,
 u'ca': 28,
 u'cat': 29,
 u'ce': 30,
 u'ce ': 31,
 u'd': 32,
 u'd ': 33,
 u'd o': 34,
 u'e': 35,
 u'e ': 36,
 u'e c': 37,
 u'e m': 38,
 u'g': 39,
 u'go': 40,
 u'goo': 41,
 u'h': 42,
 u'ha': 43,
 u'hat': 44,
 u'he': 45,
 u'he ': 46,
 u'hi': 47,
 u'his': 48,
 u'i': 49,
 u'ic': 50,
 u'ice': 51,
 u'is': 52,
 u'is ': 53,
 u'm': 54,
 u'ma': 55,
 u'mat': 56,
 u'n': 57,
 u'n ': 58,
 u'n t': 59,
 u'ne': 60,
 u'ni': 61,
 u'nic': 62,
 u'o': 63,
 u'od': 64,
 u'od ': 65,
 u'on': 66,
 u'on ': 67,
 u'one': 68,
 u'oo': 69,
 u'ood': 70,
 u's': 71,
 u's ': 72,
 u's a': 73,
 u's c': 74,
 u'sa': 75,
 u'sat': 76,
 u't': 77,
 u't ': 78,
 u't c': 79,
 u't i': 80,
 u't o': 81,
 u'

In [38]:
X = vectorizer.transform([
    "The cat sat on the mat.",
    "This cat is a nice cat.",
    "That cat is a good one",
])

In [39]:
X.toarray()

array([[0.35530476, 0.        , 0.        , 0.07106095, 0.07106095,
        0.        , 0.        , 0.        , 0.        , 0.12031665,
        0.12031665, 0.        , 0.        , 0.09150391, 0.09150391,
        0.12031665, 0.12031665, 0.12031665, 0.12031665, 0.09150391,
        0.21318286, 0.        , 0.        , 0.        , 0.21318286,
        0.1421219 , 0.09150391, 0.07106095, 0.07106095, 0.07106095,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.1421219 , 0.18300783, 0.09150391, 0.12031665, 0.        ,
        0.        , 0.        , 0.1421219 , 0.        , 0.        ,
        0.2406333 , 0.2406333 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.12031665,
        0.12031665, 0.12031665, 0.07106095, 0.12031665, 0.12031665,
        0.        , 0.        , 0.        , 0.09150391, 0.        ,
        0.        , 0.09150391, 0.12031665, 0.        , 0.        ,
        0.        , 0.07106095, 0.        , 0.  

In [40]:
# word2vec
# glove vectors
# bert