# Python numpy

In [3]:
import numpy as np

In [13]:
#array of vectors

### Initializers 

In [ ]:
# v -> [ [1,2,3,5], [4,5,6 7,], [10.8, 9.9, 0, 8] ]

In [4]:
vec = np.zeros( (2,3) )

In [5]:
vec

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
1.

1.0

In [7]:
a = np.ones((13,9))
print a

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [8]:
type(a)

numpy.ndarray

In [9]:
a.shape

(13, 9)

In [16]:
# city = ["mumbai", "delhi", "Bangalore"]
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
x.shape

(5, 5)

In [14]:
data1 = np.array([ [1.2 ,2.6, 3.99999999], [4.,5.,6.], [7,8, 9]], dtype=np.float16)
data1

array([[1.2, 2.6, 4. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]], dtype=float16)

In [16]:
type(data1)

numpy.ndarray

In [19]:
x = list(data1)

In [23]:
data1.tolist()

[[1.2, 2.6, 3.99999999], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

In [22]:
x = [[1.2, 2.6, 3.99999999], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

In [23]:
type(x)

list

In [24]:
np_x = np.array(x)

In [25]:
np_x

array([[1.2       , 2.6       , 3.99999999],
       [4.        , 5.        , 6.        ],
       [7.        , 8.        , 9.        ]])

In [51]:
np.random.normal(0, 1)

0.1563606668372211

In [52]:
%%time
length = 10000000
res = []
for i in range(length):
    res.append(np.random.normal(0, 1))

CPU times: user 19.5 s, sys: 366 ms, total: 19.9 s
Wall time: 20 s


In [53]:
len(res)

10000000

In [54]:
res[:10]

[-1.4296159141642009,
 -0.016689802026698026,
 -1.175970039258841,
 0.09215572348093623,
 -0.8235551922419632,
 0.6374208436972741,
 -1.2179611037556024,
 0.7645324119201207,
 0.11116287118812103,
 0.49617060265129387]

In [55]:
%%time
np_list = np.random.normal(0, 1, length)

CPU times: user 346 ms, sys: 3.91 ms, total: 350 ms
Wall time: 349 ms


In [58]:
np_list[:10]

array([ 0.05746985, -0.74152345, -1.76974162,  2.39456715, -1.08293722,
       -0.48287726,  1.243093  ,  0.97065747, -0.15826422,  0.19923   ])

In [57]:
len(np_list)

10000000

### Data type

In [59]:
data1

array([[1.2, 2.6, 4. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]], dtype=float32)

In [60]:
data_16 = data1.astype(np.float16)

In [61]:
data_16

array([[1.2, 2.6, 4. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]], dtype=float16)

In [27]:
float_data1 = data1.astype(np.float32)
float_data1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [28]:
float_data1.astype(np.string_)

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='|S32')

In [26]:
num_str = np.array(['11', '0.99', '44', '11'], dtype = np.float64)
num_str

array([ 11.  ,   0.99,  44.  ,  11.  ])

In [20]:
num_str.astype(np.float16)

array([  1.25      ,   0.99023438,  44.        ,  11.        ], dtype=float16)

### Operations

In [15]:
data1

array([[1.2, 2.6, 4. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]], dtype=float16)

In [63]:
data1.shape

(3, 3)

In [67]:
data9 = data1.reshape(1,9)

In [68]:
data9

array([[1.2, 2.6, 4. , 4. , 5. , 6. , 7. , 8. , 9. ]], dtype=float32)

In [38]:
data1

array([[1.2       , 2.6       , 3.99999999],
       [4.        , 5.        , 6.        ],
       [7.        , 8.        , 9.        ]])

In [16]:
data_4 = data1 + 4

In [17]:
data1

array([[1.2, 2.6, 4. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]], dtype=float16)

In [21]:
data1[0]+=4

In [22]:
data1

array([[5.2, 6.6, 8. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]], dtype=float16)

In [73]:
data2 = data1 + data1[0]
data2

array([[ 2.4,  5.2,  8. ],
       [ 5.2,  7.6, 10. ],
       [ 8.2, 10.6, 13. ]], dtype=float32)

In [75]:
data2 - 2

array([[ 0.4000001,  3.1999998,  6.       ],
       [ 3.1999998,  5.6      ,  8.       ],
       [ 6.2      ,  8.6      , 11.       ]], dtype=float32)

In [78]:
np.sqrt(data1)

array([[1.0954452, 1.6124516, 2.       ],
       [2.       , 2.236068 , 2.4494898],
       [2.6457512, 2.828427 , 3.       ]], dtype=float32)

In [77]:
data1 ** 0.5

array([[1.0954452, 1.6124516, 2.       ],
       [2.       , 2.236068 , 2.4494898],
       [2.6457512, 2.828427 , 3.       ]], dtype=float32)

In [30]:
print(data1 / 3)

print "============="
print 
print(data1 / 3.0)

[[ 0.4         0.66666667  1.        ]
 [ 1.33333333  1.66666667  2.        ]
 [ 2.33333333  2.66666667  3.        ]]

[[ 0.4         0.66666667  1.        ]
 [ 1.33333333  1.66666667  2.        ]
 [ 2.33333333  2.66666667  3.        ]]


In [24]:
print(data1 - data1/3)
print(float_data1 - float_data1/3)
print(data1 - data1/3.0)

[[ 0.8         1.33333333  2.        ]
 [ 2.66666667  3.33333333  4.        ]
 [ 4.66666667  5.33333333  6.        ]]
[[ 0.79980469  1.33398438  2.        ]
 [ 2.66796875  3.33203125  4.        ]
 [ 4.6640625   5.3359375   6.        ]]
[[ 0.8         1.33333333  2.        ]
 [ 2.66666667  3.33333333  4.        ]
 [ 4.66666667  5.33333333  6.        ]]


In [25]:
print(1.0 / data1)
print(1 / float_data1)

print(1.0 / data1)


[[ 0.83333333  0.5         0.33333333]
 [ 0.25        0.2         0.16666667]
 [ 0.14285714  0.125       0.11111111]]
[[ 0.83300781  0.5         0.33325195]
 [ 0.25        0.19995117  0.16662598]
 [ 0.14282227  0.125       0.11108398]]
[[ 0.83333333  0.5         0.33333333]
 [ 0.25        0.2         0.16666667]
 [ 0.14285714  0.125       0.11111111]]


In [27]:
data1 ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974],
       [ 2.64575131,  2.82842712,  3.        ]])

In [26]:
data1 ** 3

array([[   1.728,    8.   ,   27.   ],
       [  64.   ,  125.   ,  216.   ],
       [ 343.   ,  512.   ,  729.   ]])

In [47]:
data1

array([[1.2       , 2.6       , 3.99999999],
       [4.        , 5.        , 6.        ],
       [7.        , 8.        , 9.        ]])

In [55]:
data1[0]

array([5.2       , 6.6       , 7.99999999])

In [56]:
data2 =  data1+ data1[0]

In [57]:
data2

array([[10.4       , 13.2       , 15.99999998],
       [ 9.2       , 11.6       , 13.99999999],
       [12.2       , 14.6       , 16.99999999]])

In [79]:
ls = range(5,10)
ls

[5, 6, 7, 8, 9]

In [59]:
ls[1:3]

[6, 7]

### Indexing 

In [80]:
data2 = np.arange(5,11)
data2

array([ 5,  6,  7,  8,  9, 10])

In [82]:
data1

array([[1.2, 2.6, 4. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]], dtype=float32)

In [83]:
data1.shape

(3, 3)

In [81]:
data2.shape

(6,)

In [84]:
data2.reshape(3,2)

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [65]:
data2[:3]

array([5, 6, 7])

In [55]:
data2

array([ 5,  6,  7,  8,  9, 10])

In [56]:
data2.shape

(6,)

In [57]:
type(data2)

numpy.ndarray

In [58]:
data2

array([ 5,  6,  7,  8,  9, 10])

In [59]:
data2[1:3]

array([6, 7])

In [62]:
data3 = data2.reshape((2,3))

In [64]:
data3

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [63]:
data3[1:3]

array([[ 8,  9, 10]])

In [70]:
data2

array([ 5,  6,  7,  8,  9, 10])

In [34]:
data2[0:3]

array([5, 6, 7])

In [33]:
data2[1:4]

array([6, 7, 8])

In [35]:
data2[1:4] = [10,20,30]
data2

array([ 5, 10, 20, 30,  9])

In [69]:
data1 = data1.astype(np.int32)

In [85]:
data1

array([[1.2, 2.6, 4. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]], dtype=float32)

In [88]:
data1[:2, :2]

array([[1.2, 2.6],
       [4. , 5. ]], dtype=float32)

In [89]:
data1[1:, 1:]

array([[5., 6.],
       [8., 9.]], dtype=float32)

In [ ]:
np.ones((2))

In [ ]:
np.ones((2))

In [76]:
data1[:2, :2]

array([[5, 6],
       [4, 5]], dtype=int32)

In [81]:
data1[1:, ]

array([[4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [82]:
data1[1:, :2]

array([[4, 5],
       [7, 8]], dtype=int32)

In [68]:
data1[:2, 1:] = 0

In [69]:
data1

array([[7, 0, 0],
       [4, 0, 0],
       [7, 8, 9]], dtype=int32)

In [87]:
data1[1:, :2]

array([[4., 5.],
       [7., 8.]])

In [72]:
data1[1:, 1:] = 

array([[ 5.,  6.],
       [ 8.,  9.]])

In [82]:
data1[1:, 1:   ] = [[9,9], [9,9]]

In [83]:
data1

array([[ 1.2,  2. ,  3. ],
       [ 4. ,  9. ,  9. ],
       [ 7. ,  9. ,  9. ]])

In [71]:
data1

array([[7, 0, 0],
       [4, 0, 0],
       [7, 8, 9]], dtype=int32)

In [70]:
data1[1:, :2 ]

array([[4, 0],
       [7, 8]], dtype=int32)

In [40]:
data1[2][0]

7.0

In [40]:
data1[:2, :2 ]

array([[ 1.2,  2. ],
       [ 4. ,  5. ]])

In [51]:
data1[:2, 1:]

array([[ 2.,  3.],
       [ 5.,  6.]])

In [47]:
data1.shape

(3, 3)

In [50]:
data1[9:, 0:]

array([], shape=(0, 3), dtype=float64)

In [42]:
data1[1:3,0:2] = [[9,9], [0,1]]

In [44]:
data1

array([[ 50.,  50.,  50.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.]])

In [47]:
data1.shape

(3, 3)

In [50]:
data1.reshape(9,1)

array([[ 50.],
       [ 50.],
       [ 50.],
       [  4.],
       [  5.],
       [  6.],
       [  7.],
       [  8.],
       [  9.]])

In [92]:
data1

array([[1.2, 2.6, 4. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]], dtype=float32)

In [94]:
np.median(data1[0])

2.6

In [93]:
np.mean(data1[2])

8.0

In [95]:
np.median(data1[1])

5.0

In [96]:
np.mean([10,29,99,88])

56.5

In [81]:
data1[2,0]
data1[2,0:1]

array([10])

In [49]:
data1[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
print(data1[:2,1:])
print(data1[:2][1:])

[[2 3]
 [9 6]]
[[9 9 6]]


In [41]:
np.ones((2,9))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])