# Python numpy

### Masking

In [4]:
import numpy as np
names = np.array (['Bob', 'Joe', 'Will', 'Bob', 'Will','Joe', 'Joe'])
names.shape

(7,)

standard normal distribution    
[np.random.randn reference link](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html)

In [5]:
dataNames = np.random.randn(7,4)

In [7]:
dataNames.shape

(7, 4)

In [10]:
names == 'Joe'

array([False,  True, False, False, False,  True,  True], dtype=bool)

In [11]:
dataNames

array([[ 1.22913662, -1.34828531, -1.98025221,  0.07271133],
       [-0.76024482, -0.45091591,  1.04874781, -1.66131369],
       [-1.6642103 , -0.48739339, -1.45320062, -0.98423117],
       [ 0.37945078, -0.92161472, -0.77526241,  0.41364308],
       [-0.03277972, -0.0165099 ,  0.49428066,  0.49695947],
       [ 0.46357654,  1.3150627 , -0.72575325,  1.86045442],
       [ 0.55920249, -1.13149532, -0.70783947,  0.0834455 ]])

In [14]:
dataNames < 0 

array([[False,  True,  True, False],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True, False, False],
       [False, False,  True, False],
       [False,  True,  True, False]], dtype=bool)

In [17]:
x = dataNames[dataNames < 0 ]

In [18]:
x.shape

(16,)

In [3]:
colors = np.array(["Green", "Yellow",'Blue'])

In [33]:
colors == 'Blue'

array([False, False,  True], dtype=bool)

In [4]:
col_vector = np.eye(3)
col_vector

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [6]:
col_vector[colors == "Blue"]

array([[ 0.,  0.,  1.]])

array([[-1.32266917, -0.24117027,  0.22787929,  0.92426871],
       [ 0.76801166, -1.12463082,  1.1157425 , -0.18491516],
       [ 0.09716049,  0.61300099, -1.52936254,  0.09589474]])

In [25]:
np.random.binomial(0,1)

0

dtype('float64')

In [7]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='|S4')

In [9]:
dataNames >0

array([[False, False,  True,  True],
       [False, False,  True, False],
       [False,  True, False, False],
       [ True,  True, False,  True],
       [False, False,  True, False],
       [False,  True,  True, False],
       [False, False,  True, False]], dtype=bool)

In [8]:
dataNames[dataNames >0 ]

array([ 0.34471077,  0.49597462,  0.62478658,  1.13554263,  0.2943891 ,
        0.23998623,  3.10519931,  0.28669928,  0.64637391,  0.4730304 ,
        0.08480054])

In [10]:
dataNames[names == 'Bob', 2:]

array([[-1.08283658, -0.73889556],
       [-0.48348248, -0.17232392]])

In [11]:
dataNames[names == 'Bob', 2]

array([-1.08283658, -0.48348248])

In [17]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [7]:
dataNames[dataNames>0]  =0

In [12]:
my_fil = dataNames>0


In [13]:
dataNames[my_fil]

array([ 1.0700252 ,  1.20594198,  0.28218578,  0.25341503,  0.28692587,
        1.2350551 ,  1.05551597,  0.45145667,  0.18626074,  1.40261794,
        1.0274514 ,  0.09028096])

In [13]:
mask = (names is 'Bob') | (names is 'Will')
mask

False

In [16]:
np.array([[1,2,3], [1,2], [0]])

array([[1, 2, 3], [1, 2], [0]], dtype=object)

In [17]:
mask = (names=='Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

#### is and ==

[link](http://stackoverflow.com/questions/132988/is-there-a-difference-between-and-is-in-python)   

**==** is for value equality. Use it when you would like to know if two objects have the same value.   
   
   
**is** is for reference equality. Use it when you would like to know if two references refer to the same object.


In [18]:
dataNames[mask]

array([[-1.68468159,  1.21792479, -1.08283658, -0.73889556],
       [-1.45119246,  0.16376966, -0.24052173, -0.57333856],
       [ 0.5544647 , -0.3002093 , -0.48348248, -0.17232392],
       [-2.09553746, -0.28800138, -1.31097088, -1.15347167]])

In [22]:
a = np.arange(0,20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
dataNames

array([[ 0.        ,  0.84602686,  0.37982845,  0.54374276],
       [ 0.28992817,  0.48053509,  0.51066583,  1.46284885],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.0829676 ,  0.        ,  1.81358128],
       [ 0.27086493,  0.40519092,  0.        ,  0.09243493],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.71105098,  0.        ,  0.86072953]])

In [35]:
dataNames[dataNames<0] = 0
dataNames

array([[ 0.        ,  0.84602686,  0.37982845,  0.54374276],
       [ 0.28992817,  0.48053509,  0.51066583,  1.46284885],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.0829676 ,  0.        ,  1.81358128],
       [ 0.27086493,  0.40519092,  0.        ,  0.09243493],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.71105098,  0.        ,  0.86072953]])

In [20]:
dataNames[names != 'Joe'] = 7
dataNames

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 1.41321156,  0.        ,  0.62164341,  0.04944074],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.3669862 ,  0.        ,  0.        ],
       [ 1.34082849,  0.92380955,  0.        ,  1.35205695]])

### Simple Matrix Operations

In [17]:
dataMat = np.arange(15)
dataMat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
dataMat = dataMat.reshape((3,5))
dataMat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
dataMat.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [22]:
np.dot(dataMat, dataMat.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])